name: Render and deploy Quarto files
on:
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    container: rocker/verse:latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2

      - name: Install Python dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install -y python3-virtualenv
          sudo apt install -y python3-venv
        shell: /bin/bash {0}

      - name: Install R dependencies
        if: runner.os == 'Linux'
        run: |
          install.packages(c("rmarkdown", "jsonlite", "reticulate", "quarto"))
        shell: Rscript {0}

      - name: Setup python virtualenv
        run: |
          reticulate::virtualenv_create("testbook", packages = c("matplotlib", "numpy"))
          reticulate::virtualenv_install("testbook", "numpy",
              pip_options = c("--no-binary=numpy",  "--force-reinstall"))
        shell: Rscript {0}

      - name: "Install Quarto and render"
        uses: pommevilla/quarto-render@main

      - name: "Deploy to gh-pages"
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
